#!/usr/bin/env python3

from turtle import Turtle
from random import random

t = Turtle()
t.speed(0)
t.left(90)

def random_color():
    return (random(),random(),random())

def draw_a_tree(depth, branches):
    if depth > 0:
        t.width(5)
        t.pencolor(random_color())
        t.pendown()
        t.forward(7 * depth)
        t.left(130)
        count = 0
        while count < branches:
            t.right(180 / branches)
            draw_a_tree(depth-1, branches)
            count += 1
        t.left(50)
        t.penup()
        t.backward(7 * depth)

draw_a_tree(9,2)
input()
