#!/usr/bin/env python3

import time
import curses as c
s = c.initscr()
c.start_color()
c.cbreak()
s.keypad(1)



"""
try:
    height,width = stdscr.getmaxyx()
    num = min(height,width)
    for x in range(num):
        stdscr.addch(x,x,'X')

    # Print Hello World along the top
    stdscr.addstr(0,10,"Hello World")

    #Draw some lines
    for x in range(8):
        stdscr.addch(4,x,c.ACS_HLINE)
    stdscr.addch(4,8,c.ACS_PLUS)
    stdscr.addch(4,9,c.ACS_LRCORNER)

    stdscr.refresh()
    key = 'X'
    while key != ord('q'):
        key = stdscr.getch()
        stdscr.addch(10,10,key)
        stdscr.refresh()
"""
try:
    c.init_pair(1, c.COLOR_RED, c.COLOR_WHITE)
    s.addstr(0,0,"addstr",c.color_pair(1))
    s.refresh()
    time.sleep(3)

finally:
  c.nocbreak()
  s.keypad(0)
  c.echo()
  c.endwin()

