#!/usr/bin/env python3

import random

class Story(object):
    x = 10
    y = 20

    @property
    def z(self):
      return "2"

story = Story()

class Player():
      health = 100

player = Player()

print('{s.x} and {s.z} and has {p.health} health'.format(s=story,p=player))
